# Form implementation generated from reading ui file 'Designs\TelaPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TelaPrincipal(object):
    def setupUi(self, TelaPrincipal):
        TelaPrincipal.setObjectName("TelaPrincipal")
        TelaPrincipal.resize(800, 600)
        TelaPrincipal.setMinimumSize(QtCore.QSize(800, 600))
        TelaPrincipal.setMaximumSize(QtCore.QSize(800, 600))
        TelaPrincipal.setStyleSheet("")
        self.layoutTelaPrincipal = QtWidgets.QHBoxLayout(TelaPrincipal)
        self.layoutTelaPrincipal.setContentsMargins(0, 0, 0, 0)
        self.layoutTelaPrincipal.setSpacing(1)
        self.layoutTelaPrincipal.setObjectName("layoutTelaPrincipal")
        self.MenuLateral = QtWidgets.QWidget(parent=TelaPrincipal)
        self.MenuLateral.setStyleSheet("QWidget#MenuLateral {\n"
"background-color: #0ca5b0;\n"
"}\n"
"QPushButton{\n"
"    padding: 5px;\n"
"    font: 700 10pt \"Segoe UI\";\n"
"    background-color: #f0f0f0;\n"
"    border: 2px outset gray;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #efefef;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #ffffff;\n"
"border-style: inset;\n"
"}")
        self.MenuLateral.setObjectName("MenuLateral")
        self.botaoVerFuncionarios = QtWidgets.QPushButton(parent=self.MenuLateral)
        self.botaoVerFuncionarios.setGeometry(QtCore.QRect(40, 120, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.botaoVerFuncionarios.setFont(font)
        self.botaoVerFuncionarios.setStyleSheet("")
        self.botaoVerFuncionarios.setObjectName("botaoVerFuncionarios")
        self.botaoInserirFuncionarios = QtWidgets.QPushButton(parent=self.MenuLateral)
        self.botaoInserirFuncionarios.setGeometry(QtCore.QRect(40, 170, 120, 30))
        self.botaoInserirFuncionarios.setObjectName("botaoInserirFuncionarios")
        self.botaoAlterarFuncionarios = QtWidgets.QPushButton(parent=self.MenuLateral)
        self.botaoAlterarFuncionarios.setGeometry(QtCore.QRect(40, 220, 120, 30))
        self.botaoAlterarFuncionarios.setObjectName("botaoAlterarFuncionarios")
        self.botaoRemoverFuncionarios = QtWidgets.QPushButton(parent=self.MenuLateral)
        self.botaoRemoverFuncionarios.setGeometry(QtCore.QRect(40, 270, 120, 30))
        self.botaoRemoverFuncionarios.setObjectName("botaoRemoverFuncionarios")
        self.botaoSair = QtWidgets.QPushButton(parent=self.MenuLateral)
        self.botaoSair.setGeometry(QtCore.QRect(40, 400, 120, 30))
        self.botaoSair.setObjectName("botaoSair")
        self.rotuloMenuLateral = QtWidgets.QLabel(parent=self.MenuLateral)
        self.rotuloMenuLateral.setGeometry(QtCore.QRect(34, 20, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.rotuloMenuLateral.setFont(font)
        self.rotuloMenuLateral.setStyleSheet("color: #fefeEB;")
        self.rotuloMenuLateral.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rotuloMenuLateral.setWordWrap(True)
        self.rotuloMenuLateral.setObjectName("rotuloMenuLateral")
        self.layoutTelaPrincipal.addWidget(self.MenuLateral)
        self.CaixaConteudo = QtWidgets.QWidget(parent=TelaPrincipal)
        self.CaixaConteudo.setStyleSheet("QWidget#CaixaConteudo{\n"
"background-color: #f8f4e4\n"
"}")
        self.CaixaConteudo.setObjectName("CaixaConteudo")
        self.layoutTelaPrincipal.addWidget(self.CaixaConteudo)
        self.layoutTelaPrincipal.setStretch(0, 1)
        self.layoutTelaPrincipal.setStretch(1, 3)

        self.retranslateUi(TelaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(TelaPrincipal)

    def retranslateUi(self, TelaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        TelaPrincipal.setWindowTitle(_translate("TelaPrincipal", "Form"))
        self.botaoVerFuncionarios.setText(_translate("TelaPrincipal", "Ver"))
        self.botaoInserirFuncionarios.setText(_translate("TelaPrincipal", "Inserir"))
        self.botaoAlterarFuncionarios.setText(_translate("TelaPrincipal", "Alterar"))
        self.botaoRemoverFuncionarios.setText(_translate("TelaPrincipal", "Remover"))
        self.botaoSair.setText(_translate("TelaPrincipal", "Sair"))
        self.rotuloMenuLateral.setText(_translate("TelaPrincipal", "Sistema RH"))
