# Form implementation generated from reading ui file 'Designs\TelaVerFuncionarios.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TelaVerFuncionarios(object):
    def setupUi(self, TelaVerFuncionarios):
        TelaVerFuncionarios.setObjectName("TelaVerFuncionarios")
        TelaVerFuncionarios.resize(582, 504)
        self.layoutVerFuncionarios = QtWidgets.QVBoxLayout(TelaVerFuncionarios)
        self.layoutVerFuncionarios.setContentsMargins(20, 20, 20, 20)
        self.layoutVerFuncionarios.setSpacing(30)
        self.layoutVerFuncionarios.setObjectName("layoutVerFuncionarios")
        self.rotuloVerFuncionarios = QtWidgets.QLabel(parent=TelaVerFuncionarios)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        self.rotuloVerFuncionarios.setFont(font)
        self.rotuloVerFuncionarios.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rotuloVerFuncionarios.setObjectName("rotuloVerFuncionarios")
        self.layoutVerFuncionarios.addWidget(self.rotuloVerFuncionarios)
        self.tabelaFuncionarios = QtWidgets.QTableWidget(parent=TelaVerFuncionarios)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.tabelaFuncionarios.setFont(font)
        self.tabelaFuncionarios.setStyleSheet("")
        self.tabelaFuncionarios.setObjectName("tabelaFuncionarios")
        self.tabelaFuncionarios.setColumnCount(4)
        self.tabelaFuncionarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaFuncionarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaFuncionarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaFuncionarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaFuncionarios.setHorizontalHeaderItem(3, item)
        self.layoutVerFuncionarios.addWidget(self.tabelaFuncionarios)

        self.retranslateUi(TelaVerFuncionarios)
        QtCore.QMetaObject.connectSlotsByName(TelaVerFuncionarios)

    def retranslateUi(self, TelaVerFuncionarios):
        _translate = QtCore.QCoreApplication.translate
        TelaVerFuncionarios.setWindowTitle(_translate("TelaVerFuncionarios", "Form"))
        self.rotuloVerFuncionarios.setText(_translate("TelaVerFuncionarios", "Ver Funcionarios"))
        item = self.tabelaFuncionarios.horizontalHeaderItem(0)
        item.setText(_translate("TelaVerFuncionarios", "ID"))
        item = self.tabelaFuncionarios.horizontalHeaderItem(1)
        item.setText(_translate("TelaVerFuncionarios", "Nome"))
        item = self.tabelaFuncionarios.horizontalHeaderItem(2)
        item.setText(_translate("TelaVerFuncionarios", "Cargo"))
        item = self.tabelaFuncionarios.horizontalHeaderItem(3)
        item.setText(_translate("TelaVerFuncionarios", "Salário"))
