# Form implementation generated from reading ui file 'Design\TelaVerFuncionarios.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TelaVerFuncionarios(object):
    def setupUi(self, TelaVerFuncionarios):
        TelaVerFuncionarios.setObjectName("TelaVerFuncionarios")
        TelaVerFuncionarios.resize(598, 481)
        self.layoutVerFuncionarios = QtWidgets.QVBoxLayout(TelaVerFuncionarios)
        self.layoutVerFuncionarios.setContentsMargins(20, 20, 20, 20)
        self.layoutVerFuncionarios.setSpacing(20)
        self.layoutVerFuncionarios.setObjectName("layoutVerFuncionarios")
        self.rotuloTituloVerFuncionarios = QtWidgets.QLabel(parent=TelaVerFuncionarios)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        self.rotuloTituloVerFuncionarios.setFont(font)
        self.rotuloTituloVerFuncionarios.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rotuloTituloVerFuncionarios.setObjectName("rotuloTituloVerFuncionarios")
        self.layoutVerFuncionarios.addWidget(self.rotuloTituloVerFuncionarios)
        self.tabelaVerFuncionarios = QtWidgets.QTableWidget(parent=TelaVerFuncionarios)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabelaVerFuncionarios.setFont(font)
        self.tabelaVerFuncionarios.setObjectName("tabelaVerFuncionarios")
        self.tabelaVerFuncionarios.setColumnCount(4)
        self.tabelaVerFuncionarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaVerFuncionarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaVerFuncionarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaVerFuncionarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaVerFuncionarios.setHorizontalHeaderItem(3, item)
        self.layoutVerFuncionarios.addWidget(self.tabelaVerFuncionarios)

        self.retranslateUi(TelaVerFuncionarios)
        QtCore.QMetaObject.connectSlotsByName(TelaVerFuncionarios)

    def retranslateUi(self, TelaVerFuncionarios):
        _translate = QtCore.QCoreApplication.translate
        TelaVerFuncionarios.setWindowTitle(_translate("TelaVerFuncionarios", "Form"))
        self.rotuloTituloVerFuncionarios.setText(_translate("TelaVerFuncionarios", "Ver Funcionarios"))
        item = self.tabelaVerFuncionarios.horizontalHeaderItem(0)
        item.setText(_translate("TelaVerFuncionarios", "ID"))
        item = self.tabelaVerFuncionarios.horizontalHeaderItem(1)
        item.setText(_translate("TelaVerFuncionarios", "Nome"))
        item = self.tabelaVerFuncionarios.horizontalHeaderItem(2)
        item.setText(_translate("TelaVerFuncionarios", "Cargo"))
        item = self.tabelaVerFuncionarios.horizontalHeaderItem(3)
        item.setText(_translate("TelaVerFuncionarios", "Salário"))
