# Form implementation generated from reading ui file 'Design\JanelaPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TelaPrincipal(object):
    def setupUi(self, TelaPrincipal):
        TelaPrincipal.setObjectName("TelaPrincipal")
        TelaPrincipal.resize(800, 600)
        icon = QtGui.QIcon.fromTheme("accessories-text-editor")
        TelaPrincipal.setWindowIcon(icon)
        self.layoutTelaPrincipal = QtWidgets.QHBoxLayout(TelaPrincipal)
        self.layoutTelaPrincipal.setContentsMargins(0, 0, 0, 0)
        self.layoutTelaPrincipal.setSpacing(1)
        self.layoutTelaPrincipal.setObjectName("layoutTelaPrincipal")
        self.MenuLateral = QtWidgets.QWidget(parent=TelaPrincipal)
        self.MenuLateral.setStyleSheet("QWidget#MenuLateral {\n"
"background-color: rgb(7, 8, 24);\n"
"border: 3px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"padding:  5px 3px 5px 3px;\n"
"border: 2px outset rgb(116, 116, 116);\n"
"background-color: #f0f0f0;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(159, 159, 159)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #f2f2f2;\n"
"border-style: inset;\n"
"}")
        self.MenuLateral.setObjectName("MenuLateral")
        self.botaoVerFuncionarios = QtWidgets.QPushButton(parent=self.MenuLateral)
        self.botaoVerFuncionarios.setGeometry(QtCore.QRect(40, 150, 125, 30))
        self.botaoVerFuncionarios.setObjectName("botaoVerFuncionarios")
        self.botaoInserirFuncionarios = QtWidgets.QPushButton(parent=self.MenuLateral)
        self.botaoInserirFuncionarios.setGeometry(QtCore.QRect(40, 190, 125, 30))
        self.botaoInserirFuncionarios.setObjectName("botaoInserirFuncionarios")
        self.botaoAlterarFuncionarios = QtWidgets.QPushButton(parent=self.MenuLateral)
        self.botaoAlterarFuncionarios.setGeometry(QtCore.QRect(40, 230, 125, 30))
        self.botaoAlterarFuncionarios.setObjectName("botaoAlterarFuncionarios")
        self.botaoRemoverFuncionarios = QtWidgets.QPushButton(parent=self.MenuLateral)
        self.botaoRemoverFuncionarios.setGeometry(QtCore.QRect(40, 270, 125, 30))
        self.botaoRemoverFuncionarios.setObjectName("botaoRemoverFuncionarios")
        self.botaoSair = QtWidgets.QPushButton(parent=self.MenuLateral)
        self.botaoSair.setGeometry(QtCore.QRect(40, 350, 125, 30))
        self.botaoSair.setObjectName("botaoSair")
        self.logoMenuLateral = QtWidgets.QLabel(parent=self.MenuLateral)
        self.logoMenuLateral.setGeometry(QtCore.QRect(30, 10, 140, 101))
        self.logoMenuLateral.setStyleSheet("font: 700 24pt \"Segoe UI\";\n"
"color: white;")
        self.logoMenuLateral.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoMenuLateral.setWordWrap(True)
        self.logoMenuLateral.setObjectName("logoMenuLateral")
        self.layoutTelaPrincipal.addWidget(self.MenuLateral)
        self.CaixaConteudo = QtWidgets.QWidget(parent=TelaPrincipal)
        self.CaixaConteudo.setStyleSheet("")
        self.CaixaConteudo.setObjectName("CaixaConteudo")
        self.layoutTelaPrincipal.addWidget(self.CaixaConteudo)
        self.layoutTelaPrincipal.setStretch(0, 1)
        self.layoutTelaPrincipal.setStretch(1, 3)

        self.retranslateUi(TelaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(TelaPrincipal)

    def retranslateUi(self, TelaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        TelaPrincipal.setWindowTitle(_translate("TelaPrincipal", "Sistema RH"))
        self.botaoVerFuncionarios.setText(_translate("TelaPrincipal", "Ver Funcionarios"))
        self.botaoInserirFuncionarios.setText(_translate("TelaPrincipal", "Inserir Funcionario"))
        self.botaoAlterarFuncionarios.setText(_translate("TelaPrincipal", "Alterar Funcionario"))
        self.botaoRemoverFuncionarios.setText(_translate("TelaPrincipal", "Remover Funcionario"))
        self.botaoSair.setText(_translate("TelaPrincipal", "Sair"))
        self.logoMenuLateral.setText(_translate("TelaPrincipal", "Sistema RH"))
